### ISSUE TITLE
[List view] Cost model radio group filter

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools-list#110]
In [list view](https://wai-authoring-tools-list.netlify.app/tools-list/authoring/) the cost model is presented as a radio group but they don't appear to be grouped. These would probably be more appropriate to present these as checkboxes to allow for multiple selections and also for deselecting.

**Comment by SteveALee** [comment]
That's an error as I did not touch the filters. Cost Model has been removed and subsumed into Licence.
