### ISSUE TITLE
[List view] Feature filters necessary?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools-list#112]
In [list view](https://wai-authoring-tools-list.netlify.app/tools-list/authoring/) I wonder if the features are necessary to filter on. Partly because there are so many and partly because it isn't necessarily clear what would be filtered given that 'Partial' is an option when submitting a tool.

**Comment by SteveALee** [comment]
That's a valid design question requiring some clarity of purpose. I agree as they are they are of limited use and dubious value.

My hunch is the main purpose is to present the tools with good accessibility and encourage others to improve their tools. Surely no-one will want to filter on specific ATAG criteria.

So yes I agree, lets remove them.

Maybe we could add a score to each list? But there are probably issues with that too.

**Comment by SteveALee** [comment]
A slight question if "license" is the right name give the values - more "license cost" perhaps. Anyway I'm not changing that.
