### ISSUE TITLE
Submission form failures

### ISSUE THREAD

**Issue by davewallace** [w3c/wai-authoring-tools-list#140]
I've just tried completing an entry for our product into the tool and took a good amount of time populating the form fields with full answers - but unfortunately when I got to the end of the form and tried to submit - I just get landed on an error page (see attached screenshot).

First, Pre-submission state:
![image](https://user-images.githubusercontent.com/1988022/214452999-7e3642f9-b690-4f0d-bdd9-8eb026bc3b6f.png)

Then, Submission overlay works.

Then, Post-review-submission state:
![image](https://user-images.githubusercontent.com/1988022/214453758-100ad9d3-2517-4dc4-a4ec-a3ce2406cdf9.png)

Best I can help with in understanding the error, is the output in dev console captured in above screenshot, but that might not be relevant.

I thought I had lost all of my input, however navigating Back with the browser, I was able to land on the completed but not submitted form, I attempted re-submission but it fails still. I have the browser tab open still, so I can possibly help debug further with some instructions on what you'd like me to test.

I'm on Chrome latest and macOS latest, no extensions currently enabled, no other tools installed/running that would affect my web browsing experience.

**Comment by shawna-slh** [comment]
@davewallace We're very sorry that the bug caused you extra work and annoyance. We did fix a bug last week, and several test submissions worked. However, we've just gotten a report of another not working and we haven't figured that out yet.

If you want to submit tests with just a small sub-set of the data, you are welcome to. Just put at the beginning of the description: TEST

Hopefully we'll get it figured out soon.
