### ISSUE TITLE
some descriptions missing

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-authoring-tools-list#161]
Listing: Craft CMS at https://www.w3.org/WAI/tools-list/authoring/

JSON: https://github.com/w3c/wai-authoring-tools-list/blob/master/_data/wai-authoring-tools-list/submissions/8f43a1e0-d4a5-11ed-81a4-cd322f47865b.json

From Lupe: some descriptions aren’t showing on the page, although they’re showing in the JSON file. Specifically, all the answers that are marked “Partially” after “Alternative content available to editors.”

**Comment by shawna-slh** [comment]
thanks @iadawn! I merged, published, and confirmed working.

**Comment by gcamacho079** [comment]
Thanks, @shawna-slh and @iadawn!
