### ISSUE TITLE
Introduction paragraph: make larger, add more description

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-authoring-tools-list#17]
**Text under H1:**  could be larger or made more noticeable somehow e.g. in a summary box as displayed on some pages e.g. https://www.w3.org/WAI/fundamentals/components/

**Actual text:**  Browse tools that create web content, like CMSes and LMSes, website creators, discussion forums and other authoring tools, and filter for accessibility features.

**Suggestion - add some more description:** 

This page allows you to browse tools that create web content (for example, website creation tools, CMS, LMS, discussion forums and so forth).  A set of filters allows you to select the parameters of your choice.

If you are new to accessibility, consult the WAI resource for guidance on [selecting an authoring tool with accessibility features](https://wai-authoring-tools.netlify.com/authoring-tools/selecting).

This collection of tools is based on a voluntary submission process.  If you have accessibility features in your product, please submit your tool to this list.  Note:  This collection is not W3C endorsed, see the disclaimer.  SUBMIT A TOOL (button)

**Comment by hidde** [comment]
Hi Vicki, I've updated the issue title slightly to summarise the issue. Thanks for the feedback and suggested text updates, much appreciated. I suspect others may have thoughts on this intro paragraph too, so am leaving this issue open for further feedback.

**Comment by vmmiller** [comment]
Thanks, Hidde!

**Comment by slhenry** [comment]
+1 to Vicki's suggestion in general -- make the text easier to read and understand for people who land on this page without context. (I didn't review Vicki's specific wording yet)

**Comment by yatil** [comment]
-1 I find position translates that this is important text. Making it longer and/or bigger just pushes the content down the page, for which we always get push back.

(That said, I’d be open to bump up the text size for the whole WAI Website 16px – in relative units, of course, feels tiny in 2019 :-D)

**Comment by vmmiller** [comment]
Brainstorming following the reactions to adding more text, positive for some (by making the page more informative) and negative for others (by pushing the Browse Tools below the fold):

Currently, the page has two functions:
- Search/Browse for tools
- Submit a tool

I feel it important to make these two functions clear. So, another idea, perhaps, we need a landing page which links off to 
- Search/Filter/Browse and 
- Submit a tool


-

**Comment by hidde** [comment]
I've made the intro text slightly larger, and I think this makes it better.

For now I have not changed the text, because it makes it significantly longer. The more words we use there, the less space (both cognitive space in user's heads, and visual space in the design) is available for the primary purpose of the page: browsing and filtering authoring tools. 

If we feel we should explain more, I'd suggest we do it somewhere else, like on the “Selecting Authoring Tools” page.

> Currently, the page has two functions: 
>     Search/Browse for tools
>     Submit a tool

I agree these two functionalities agree, but don't think they are equal.

How I understand it, search/browse is the **primary** function and submit is a **secondary** function. This is also communicated visually, as the primary thing is most of the page, and the secondary thing is just a button that is aligned away from the rest.

**Comment by hidde** [comment]
@vmmiller @slhenry Give my last comment, could you share how strongly you feel about this? If you're ok with situation as is, feel free to indicate that, and I'll close this issue.

**Comment by slhenry** [comment]
Please leave it open. Sorry I haven't been able to get to it.

**Comment by hidde** [comment]
Ok, will leave 'waiting for input' tag on for now.

**Comment by bakkenb** [comment]
I know this is a completely different issue, but Eric opened the can of worms...

> (That said, I’d be open to bump up the text size for the whole WAI Website 16px – in relative units, > of course, feels tiny in 2019 :-D)

I officially +1 this idea!
