### ISSUE TITLE
Name of tool: should we a different word than “authoring tools”?

### ISSUE THREAD

**Issue by hidde** [w3c/wai-authoring-tools-list#2]
In conversations over the past months, I found “authoring tool” is not a well known concept outside the world of W3C and accessibility standards. My hypothesis is that many who procures/use/build authoring tools know these tools by a different name.

Additionally, “authoring tool list” is a long title, and its abbreviation (AT list) would be very confusing, because it will make accessibility people think of assistive technologies.

To reach many more people and make the resource easier for people to find , we should probably consider a different word instead of “authoring tool”.

**Comment by hidde** [comment]
Suggestions from EO call: 

* Editing Tools List
* Content Creation Tools List
* CMS & Publishing Tools List

**Comment by daniel-montalvo** [comment]
In [Minutes for August 2nd Teleconference](https://www.w3.org/2019/08/02-eo-minutes#authoring-tools-list-requirements) there are a couple of suggestions made by Helen:

> Creative Tools = CT?

Let me add some more:
* Editing Tool (possibly added by Shawn, not sure).
* Publishing Tool.
* Content Creation Tool.

**Comment by hidde** [comment]
Thanks @daniel-montalvo for the additions!

As I mentioned above, I think discoverability is essential, so one thing we need to keep top of mind is: “what would people search for?”

**Comment by eoncins** [comment]
Would the use of a different term not interfere with ATAG (Authoring Tool Accessibility Guidelines)?
The problem might be in using the acronym "AT" not the term "Authoring Tool".

**Comment by slhenry** [comment]
Yeah, this is a challenge. Naming resources can be difficult.

Probably we'll want to go with
> short name: longer title

or

> acronym and long title

For example:
* [WCAG-EM Report Tool: Website Accessibility Evaluation Report Generator](https://www.w3.org/WAI/eval/report-tool/#/)
* [Web Accessibility Perspectives: Explore the Impact and Benefits for Everyone](https://www.w3.org/WAI/perspective-videos/)
* [Developing Websites for Older People: How Web Content Accessibility Guidelines (WCAG) 2.0 Applies](https://www.w3.org/WAI/older-users/developing/)

**Comment by slhenry** [comment]
> So my suggestion would be to have the word ”accessible” in the title, and probably “accessible CMS”.

I *think* most of the tools listed will not be fully accessible, therefore, I think can't go with simply "“accessible CMS”"

**Comment by slhenry** [comment]
> Would the use of a different term not interfere with ATAG (Authoring Tool Accessibility Guidelines)?

I think it would be good to try to get "Authoring Tool" in at least the long title or sub-title.

Possibly something like:
> CMS and other Authoring Tools

**Comment by slhenry** [comment]
In case it helps with brainstorming:

* [definition of authoring tool](https://www.w3.org/TR/ATAG20/#def-Authoring-Tool)
* [ATAG Overview](https://www.w3.org/WAI/standards-guidelines/atag/)

**Comment by yatil** [comment]
I started two twitter polls to see what people not in the inner circle think:

* https://twitter.com/yatil/status/1179673332309987328
* https://twitter.com/yatil/status/1179673499897651200

**Comment by hidde** [comment]
Thanks, Eric!

**Comment by yatil** [comment]
So from my followers (skewed _towards_ accessibility, standards, and development):

* [Do you think you know what an “Authoring Tool” is?](https://twitter.com/yatil/status/1179673332309987328)
  * Yes: 52%
  * No: 48%
  * Votes: 50

* [Have you ever searched online for an “Authoring Tool”?](https://twitter.com/yatil/status/1179673499897651200)
  * Yes: 18%
  * No: 82%
  * Votes: 34

While being only an indicator, half of the followers not knowing what an Authoring Tool is means that for the general public it is probably not useful to use “Authoring Tools” in the name. In addition people seem to just not search for it. As Patrick Lauke puts it “[the term is to broad and too vague](https://twitter.com/patrick_h_lauke/status/1179730001526173696)” and he would search for “[the kind of thing i, as an end user, was thinking about authoring](https://twitter.com/patrick_h_lauke/status/1179731739326996480) […] [spreadsheet editor? word processor? website generator? blog engine? that sort of thing...](https://twitter.com/patrick_h_lauke/status/1179731977253130241)”. 

I don’t think it is a problem to use Authoring tools, with description, somewhere on the page, but people will not get it from the page title. I think it is important to have a short title, no subtitle if we can help it, and not another acronym people have a hard time to remember. Brainstorming:

* Content Management Tools
* Content Publishing Tools
* Tools for publishing content
* Accessibility of Content Publishing Tools
* List of Accessibility features of Content Publishing Tools
* Accessibility of and from Content Publishing Tools – A List

(One of the issues is that we have both, the accessibility of the tool and the accessibility of the content created by the tool. It is hard to capture that succinctly.)

**Comment by slhenry** [comment]
> I think it is important to have a short title, no subtitle if we can help it

I think a big issue is SEO. I wonder if it's important to get terms in the <h1> -- even if styled as a quiet subtitle?

**Comment by shawna-slh** [comment]
EOWG did not reach consensus on a different name for this list.
