### ISSUE TITLE
Is submit button too far off to the right?

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-authoring-tools-list#21]
Maybe this is too far off to the right.

**Comment by hidde** [comment]
I think it is good to use right alignment for some of our actions, including the 'Submit a tool' button.  It reinforces the grid and leaves the action visually distinct from the introductory paragraph (by not being close to it).

If it is less to the right it would not align on the grid, I think that's not great. If it is fully to the left, that could work.

Leaving this open for further feedback from others.

**Comment by slhenry** [comment]
+1 for not over on the right.

Fully to the left is fine.

We want it clearly visible -- even for non-tool vendors, it's good to show that we encourage anyone to submit their tool :-)

Also, screen magnification users could miss it all together if it's floating over there on the right.

**Comment by hidde** [comment]
Moving it to the left makes it less visually distinct. I agree we should not have parts of the interface be far away from everything else, for screen magnification users, but I don't think it actually _is_ far away. 

In current design the left has one purpose: get people to understand where they've ended up. The right has another purpose: call people to action. If we have both of those things on the left, that increases cognitive load.

This is a very common pattern, see also this Issue interface on GitHub. The heading for an issue is on the left, the actions (Edit/New Issue) are on the right.

**Comment by hidde** [comment]
@vmmiller @slhenry How do you feel about this issue given my last comment?

**Comment by slhenry** [comment]
Not convinced either way yet. :-) Would like to gt more input from EOWG.

**Comment by vmmiller** [comment]
I think it would be good to get more feedback from EOWG on this one.

**Comment by shawna-slh** [comment]
Following the approach agreed upon by EOWG for https://www.w3.org/WAI/courses/list/
