### ISSUE TITLE
Disclaimer missing

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-authoring-tools-list#33]
+1 to having a short, succinct "disclaimer" at the top with a link to a more detailed disclaimer  lower in the page

(fyi, in the past, EOWG spent quite a bit of time discussing options for this)

however, the more detailed one is missing ;-)

**Comment by yatil** [comment]
This should just link to a common disclaimer page that we can use for all such lists.

**Comment by slhenry** [comment]
> This should just link to a common disclaimer page that we can use for all such lists.

Not sure whether or not I agree.

The disclaimer is really important. I guess people would be less likely to click on it if it goes to another page.

Also, I think we want it to appear when these pages are printed.

**Comment by yatil** [comment]
>> This should just link to a common disclaimer page that we can use for all such lists.

> Not sure whether or not I agree.

I think it would make sense to have a really short summary on the page that then links to the “Disclaimer for Vendor-Submitted Content”. It would make it easier to identify the same types of disclaimers, so people don’t have to worry about differences between resources. 

> The disclaimer is really important. I guess people would be less likely to click on it if it goes to another page.

If the summary is really good, they would not have to unless they are interested in the exact legalese. I think it could remove a (admittedly tiny) barrier to use the lists even. 

> Also, I think we want it to appear when these pages are printed.

Again, with a good summary and the link (which is expanded to show the full URL in print), this might be covered. (As a user I always find it mildly annoying to be forced to print repetitive information, especially if it is multiple paragraphs of it.

**Comment by hidde** [comment]
I think having a "Disclaimer for Vendor-Submitted Content" page would be great, and have changed the link text in the Authoring Tools List to be exactly that text. I think it says in very few words what we need.

The user need for having a disclaimer, I think, is to be sure users of our lists can trivially figure out that this content is not W3C-vetted/endorsed and that it is vendor-submitted. And yes, I fully agree this is very important and we need to do it.

I think our need for wanting to explain in detail what the exact legal disclaiming situation is, is also valid, but I think that's more our need than the user's. For those users who do want the details, they can easily find them as they are linked.

So, my proposal would be: to have two things:

* In the Authoring Tools List: a link text that is extremely clear, like “Disclaimer for Vendor-Submitted Content”
* Somewhere else: a full disclaimer that is very precise about what these lists indicate, whether W3C verifies accuracy, whether the list if definitive, whether it can change or not, what this list says about quality, whether we endorse or not, etc (these are all examples from the Evaluation Tools List)

cc @nitedog

**Comment by shawna-slh** [comment]
For now, following the approach that EOWG agreed upon for https://www.w3.org/WAI/courses/list/

Except up front disclaimer text is more important, so included in the intro for now. Can revisit later if it becomes a priority.
