### ISSUE TITLE
Filter section heading

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-authoring-tools-list#34]

**Comment by hidde** [comment]
Are you suggesting the filter section should have a heading? 

I'm not opposed to it, it could probably benefit users navigating by heading, but would suggest we don't display it visually, as it would take up space, while, arguably, being redundant (because the section looks sufficiently like filters).

**Comment by slhenry** [comment]
It looks like filters to those who know it's filters. :-)

However, for new people coming to this list without any context, it's not at all clear.

I feel strongly that a visible heading is needed.

**Comment by hidde** [comment]
My assumption is those who don't know what filters are, will know it without (visually) explicitly saying they are filters.

Filters are extremely common on the web, and people use them for tasks like booking travel or buying stuff and more. Arguably, the group of people who are looking for accessible authoring tools are _a subset of_ and _more tech savvy_ than the group of people that recognises filters and how they work.

With heading:

<img width="1175" alt="screenshot with heading above filters" src="https://user-images.githubusercontent.com/178782/68850065-91ab2500-06d3-11ea-8343-3c7bad12b721.png">

Without heading:

<img width="1194" alt="screenshot without heading above filters" src="https://user-images.githubusercontent.com/178782/68850361-2dd52c00-06d4-11ea-8923-c5f934be6e4a.png">

**Comment by slhenry** [comment]
I note the filters and the list also need h2s structurally 

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwai-authoring-tools.netlify.com%2Fauthoring-tools%2F&showoutline=yes#headingoutline

I think the list h2 can be not visible

**Comment by hidde** [comment]
Good point, will fix!

**Comment by hidde** [comment]
Headings now exist… maybe heaving a 'Filters' heading can be agenda item for EOWG on Friday, @slhenry ? (Have added it under +agenda label for this reason)

**Comment by slhenry** [comment]
> agenda item for EOWG on Friday

Would need to coordinate that with Co-Chairs, and I think they are not available this afternoon.

**Comment by bakkenb** [comment]
Thanks for working to organize this Hidde. I agree with Shawn that we need to work on this a bit more before bringing back to the group. Work on the static examples of the tabs and other solutions that you feel would be appropriate and lets discuss on Wednesday at planning.

**Comment by hidde** [comment]
Unrelated to this issue, which is about the 'filter' heading, but just for completeness sake, I have added a proposal for tabs here: https://github.com/w3c/wai-authoring-tools/issues/49#issuecomment-555224273 

With regards to the filter issue: what further work would you suggest? I think we need to choose between: 

- having a visible header ‘Filter’ above the filters
- having an invisible header ‘Filter’ above the filters

This seems like a good thing for EOWG to decide.

**Comment by bakkenb** [comment]
Personally, I prefer a visible header above the filters.

**Comment by shawna-slh** [comment]
moot for now. If we add filters later, will probably go with the decisions of EOWG for https://www.w3.org/WAI/courses/list/
