### ISSUE TITLE
Layout does not work in Edge and IE

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools-list#43]
Much as I would love to be using a different browser, I am limited in my work environment. Unfortunately this has highlighted that the current version does not render well in Edge or IE 1

![authoring_tools_edge](https://user-images.githubusercontent.com/2444840/67024332-23873880-f0fc-11e9-8c44-a848630d079c.png)
![authoring_tools_ie](https://user-images.githubusercontent.com/2444840/67024333-23873880-f0fc-11e9-9601-a7a011f7e788.png)

**Comment by hidde** [comment]
Thanks, this is a known issue, they don't support some of the CSS properties I've used, this will be addressed in the version that goes live.

**Comment by iadawn** [comment]
The problem is that this makes it difficult for me to comment on the resource. I only have access to Edge and IE at work. I do have an opportunity to review from home, but that is only on Friday mornings.

**Comment by hidde** [comment]
Ah, I am sorry to hear that! Sadly, there is no “quick fix”., but will see if I can try and address it earlier than before live.

**Comment by iadawn** [comment]
Appreciate that. I will see if I can find different times to do any work that requires me to comment on this tool specifically.

**Comment by shawna-slh** [comment]
Is this still an issue? Is it addressed in https://www.w3.org/WAI/courses/list/ ? If so, can we use that code?
