### ISSUE TITLE
Add Pagination

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools-list#45]
It is not clear what pagination will look like as there are only 9 tools presented. What is the design solution for this?

**Comment by hidde** [comment]
Adding this to backlog (cc @nitedog). 

In the first iteration, we will likely have less than 9 tools and no pagination will be needed. That makes me think we could launch without this feature and add it in a later version.

**Comment by shawna-slh** [comment]
EOWG discussed problems with pagination for the course list. Not likely to be an issue with the list for quite some time. If so, we can use the soluction from the course list.
