### ISSUE TITLE
Terminology in filters

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools-list#47]
When used as filter items the short form descriptions of ATAG criteria sometimes do not make sense.

Most particularly:

* Non-web-based functionality is accessible
* Enough time
* Alternative content available to editors
* Preserves accessibility information
* Accessible content production is possible
* Editors guided

**Comment by hidde** [comment]
(edited your comment because somehow the 'Enough time' did not show as a bullet item)

**Comment by hidde** [comment]
Thanks @iadawn,  this is great feedback. These are all based on [ATAG 2](https://www.w3.org/TR/ATAG20), but short form, as you say and can use improvement.

I'm very open to suggestions to make them better. I also hope to simultaneously address this issue also by linking to [the page with explanations of the features](https://wai-authoring-tools.netlify.com/authoring-tools/selecting#features).

**Comment by hidde** [comment]
In #18, 'Enough time' was also flagged.

**Comment by shawna-slh** [comment]
these were removed from filters
