### ISSUE TITLE
Privacy statement

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools-list#52]
The form captures personal information. In the UK at least, I believe this would require a privacy statement.

Happy to be told wrong :)

**Comment by hidde** [comment]
I think you're absolutely right. Adding for EOWG discussion, as I suspect we may have dealt with this before in other places.

**Comment by shawna-slh** [comment]
No privacy. All public.
> When you submit the form, the data is publicly available in GitHub.
> This comment will be publicly available in GitHub, and not published on the tools list.
[ ]  I give permission for my information to be published in the W3C's authoring tools list.
