### ISSUE TITLE
Errors aren't reported if the section is closed

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-authoring-tools-list#54]
On the submit a tool form sections can be expanded and collapsed. If a section is collapsed and it contains an error then no information will be displayed to the user.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Brave
 - Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)

**Comment by shawna-slh** [comment]
ex-col reemoved
