### ISSUE TITLE
(Print only) Display selected filters

### ISSUE THREAD

**Issue by hidde** [w3c/wai-authoring-tools-list#60]
As suggested by @slhenry in #35, display what the selected filter criteria are, and show this only in the printed version.

**Comment by hidde** [comment]
Note that this already exists currently, as the checkboxes convey a selected state which also gets printed (it seems, have tested in a few browsers).

Arguably, display this information separately would be useful information for any view, not just the print version? 

I like the suggestion, but would like to suggest we do this in a later iteration. (cc @nitedog)

**Comment by shawna-slh** [comment]
closing as out of scope.
