### ISSUE TITLE
Authoring Tool Clarification List

### ISSUE THREAD

**Issue by HelenBurge** [w3c/wai-authoring-tools-list#62]
Adding the starting point of a Authoring Tool clarification list to ask for feedback on the definitions and missed items.

1.	Content management system (CMS): software that helps users create, manage, and modify content on a website without the need for specialized technical knowledge.
2.	Learning management system (LMS): software application for the administration, documentation, tracking, reporting, and delivery of educational courses, training programs, or learning and development program
a.	eLearning Authoring Tool: software package which developers use to create and package e-learning content deliverable to end users
b.	Integrated Learning Platforms: interactive online services that provides the teachers, learners, parents and others involved in education with information, tools and resources to support and enhance educational delivery and management
c.	Microlearning: relatively small learning units and short-term learning activities
3.	Forum or discussion software: online discussion site where people can hold conversations in the form of posted messages
4.	Website creators: tools that typically allow the construction of websites without manual code editing
5.	Wiki: a knowledge base website on which users collaboratively modify content and structure directly from the web browser
6.	Social Media: interactive computer-mediated technologies that facilitate the creation and sharing of information, ideas, career interests and other forms of expression via virtual communities and networks
a.	Media sharing: website and storage that allow people share multimedia files
b.	Webpage creation: hosted in the social media provider, but allows basic CMS for creating a page
c.	Internal social network: hosted in the social media application or website, as an intranet for employees to share information, connect and learn with no external access to the network
d.	Microblogging: hosted site for creating short but frequent posts to a microblog
e.	Blog comments: hosted blogs that allow comments from other people
f.	Forums: hosted online discussion site where people can hold conversations in the form of posted messages

**Comment by shawna-slh** [comment]
beyond the scope of this list to refine definitions
