### ISSUE TITLE
Radio buttons for Cost model are not working correctly

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-authoring-tools-list#63]
[… @yatil removed non-filled out issue template, the actual issue is below …]

**Comment by cochfarf** [comment]
The Cost model radio buttons are not grouped correctly so that only one can be selected at a time. The name attributes are all unique in the code. If multiple cost models can be selected then they should be checkboxes since once selected the radio buttons can't be unchecked the way they are now.

**Comment by hidde** [comment]
Thanks for reporting, this is because I took a shortcut in my template code. Keeping this issue open as it needs fixing at some point.

**Comment by shawna-slh** [comment]
? is this still an issue ?
