### ISSUE TITLE
Simplify and explain the various ACT filter values

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-authoring-tools-list#79]
Maybe make optional filters or not filters? And add "i" explanations.

"There's a lot of detail that I wouldn't want to read through in order to filter the results - I'd expect to read this level of detail as I explore the results. However, segmenting "content editor" from "end user" makes absolute sense to call out, since it will even trigger the user to think more specifically about their requirements. "

"the types of information listed does not seem particularly helpful when so many are very similar. Maybe this is because the wording is just placeholder wording right now?.?.

**Comment by shawna-slh** [comment]
mega filters removed.
