### ISSUE TITLE
Add comparison view

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-authoring-tools-list#8]
I think some people would like a comparison view of tools -- that is, see data for multiple tools in a table, e.g., http://kensgists.github.io/apt/

/me was recently comparing laptops and used that a lot.

Ideally probably we let people select tools that they want to compare.

Not sure we'll be able to get that in first release. At least I think we want it on a wish-list for later. ;-)

**Comment by hidde** [comment]
Great idea, +1 for putting in not the first release

**Comment by eoncins** [comment]
+1 to visual comparison in a further release if not possible in the first

**Comment by shawna-slh** [comment]
good idea. however, deemed out of scope.
