### ISSUE TITLE
Include date submitted

### ISSUE THREAD

**Issue by slewth2** [w3c/wai-authoring-tools-list#82]
Suggestion: Add "date posted" information in details for each Authoring tool on the list
Rationale: Will give users a sense of how up-to-date the list and tool information is, given that the accessibility of the tools can/will change over time.

**Comment by SteveALee** [comment]
A date fields is added by the submission process. this need to be displayed in the list

**Comment by shawna-slh** [comment]
It's now there near the top of expanded details.
