### ISSUE TITLE
[ED-med-data] Change field title

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-authoring-tools-list#84]
In the "About the tool" section, for clarity, I would suggest changing "Name" to "Tool Name" for the title of that field. It just makes it more clear that this should not be someone's name, but the name of the authoring tool itself.

**Comment by SteveALee** [comment]
@bakkenb Thak you. I also spotted that as the preview had two "names" :)

@shawn what casing should be used? I used "Tool name" to match other fields.
