### ISSUE TITLE
[HIGH-data] License type selection - should match filter

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-authoring-tools-list#85]
On the Authoring Tools List page, the Licensing filter has the following checkboxes:
- Open source
- Commercial
- Enterprise
- Trial or demo available

Shouldn't those also be the options to select from in the submission form? If not, I don't think the filter will work. Right now it is a open text field.

**Comment by iadawn** [comment]
For consistency it may be worth changing the options to match the evaluation tools license options:

![image](https://user-images.githubusercontent.com/2444840/199696326-1363468d-91ac-4e82-b8bd-36d0988e76b3.png)

**Comment by SteveALee** [comment]
Will not add "other" edit field for now as complicated.

**Comment by SteveALee** [comment]
@iadawn Am going to remove cost model field as they clash - is that OK?

**Comment by iadawn** [comment]
I wonder if the better field to remove is the free text License field and then just adjust the 'Cost model' field to align to the evaluation tools license field?

**Comment by SteveALee** [comment]
work for me - though edit field for other might be a bit tricky given I have no time :)- not sure

**Comment by SteveALee** [comment]
Done but left other out completely

**Comment by SteveALee** [comment]
@iadawn the CSS needs fixing as I had to use a field set (best practice anyway)

**Comment by iadawn** [comment]
Ok, will take a look in a bit
