### ISSUE TITLE
[HIGH-UI] No Form Submission Confirmation

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-authoring-tools-list#86]
I completed a test submission. There is no confirmation page or modal to let you know that the submission was collected, successful, copy of the data, or anything. 

All of the validations worked for required fields and final acknowledgment check boxes, but when I clicked the "Submit Your Tool" button the page just reloaded with a new empty form. Some sort of confirmation needs to be added.

**Comment by SteveALee** [comment]
Er, what was tried? The current preview is non functional. I am working on getting it to work after any UI updates from Kevin.

**Comment by shawna-slh** [comment]
Thanks, Steve. Hopefully the UI updates from @iadawn don't impact you getting it to work. :-)

We are hoping to publish and announce the submission for this week!

**Comment by iadawn** [comment]
@SteveALee my plan was not to change anything in the UI that would have a big impact on the functionality. It should be ok to work on them in parallel.

**Comment by SteveALee** [comment]
Yup, working in parallel, just more complex than I expected. Submissions should be good to go this week.

**Comment by SteveALee** [comment]
fixed in latest preview - https://wai-authoring-tools-list.netlify.app/tools-list/authoring/submit-a-tool/
