### ISSUE TITLE
Need a mailing list for evaluation tools

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-authoring-tools-list#89]
For now the text in the submission failure page uses - group-wai-list-evaluation-tools@w3.org

**Comment by shawna-slh** [comment]
I'm not seeing the text of the failure page to see it in context. I'm assuming it should be:

group-wai-list-authoring-tools@w3.org

**Comment by SteveALee** [comment]
Great, that is what I used

https://raw.githubusercontent.com/w3c/wai-authoring-tools-list/master/content/failure.md
