### ISSUE TITLE
URI & nav

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-authoring-tools-list#90]
URI for submission form:
**https://www.w3.org/WAI/tools-list/authoring/submit-a-tool**

<hr>

_optional more info:_

Hey @SteveALee Please plan on this for URI for authoring tools list itself:

**https://www.w3.org/WAI/tools-list/authoring**

(and will put new eval tools list at https://www.w3.org/WAI/tools-list/evaluation or maybe https://www.w3.org/WAI/tools-list/eval)

For submission form... hummm.
old eval tools list is .../submission and course list is .../submission/
unpublished draft new eval tools has used .../submit-a-tool and this repo has .../submit-a-tool
I'm not feeling strongly either way. Let's go with the more friendly "submit-a-tool".

**https://www.w3.org/WAI/tools-list/authoring/submit-a-tool**

**Comment by SteveALee** [comment]
done note also

https://www.w3.org/WAI/tools-list/authoring/submit-a-tool/failure
https://www.w3.org/WAI/tools-list/authoring/submit-a-tool/success
https://www.w3.org/WAI/tools-list/authoring/selecting

**Comment by SteveALee** [comment]
@shawna-slh @iadawn  note the new URIs will be in the latest preview

**Comment by shawna-slh** [comment]
Hey @SteveALee We haven't decided yet what to do with https://www.w3.org/WAI/tools-list/authoring/selecting
Better if it's not on the WAI website for now. Do you remember where there was a link to it? I can revise that.

**Comment by SteveALee** [comment]
yes was a link to selecting n submission page - removed link and no longer published
